#!/bin/bash

set -eu
set -o pipefail

SDPATH="$(dirname "${BASH_SOURCE[0]}")"
if [[ ! -d "${SDPATH}" ]]; then SDPATH="${PWD}"; fi
readonly SDPATH="$(cd -P "${SDPATH}" && pwd)"

WORKSPACE_PATH="${SDPATH}/.."
readonly WORKSPACE_PATH="$(cd "${WORKSPACE_PATH}" && pwd)"

CMD=("${BAZEL_REAL}" "$@")
echo + "${CMD[@]}" && "${CMD[@]}"
